### ISSUE TITLE
Debug Post Processing Material

### ISSUE THREAD

**Issue by Adhil-Suresh** [arigo/ShaderDebugger#1]
Hi the ShaderDebugger is working fine but can you make it to work with postprocessing material shader

**Comment by arigo** [comment]
Hi!  A user of ShaderDebugger, great :-)  I haven't looked at postprocessing shaders so far, but I'll try to see what needs to be done for them.

**Comment by Adhil-Suresh** [comment]
Thank you so much

**Comment by arigo** [comment]
Should be done.  It turned out to be relatively easy.  Note that as usual it only works in the Scene view, so you need to make sure your post-processing effect shader also runs in the Scene view (see demo in Assets/ShaderDebugger/Demo PostProcessing/).
