### ISSUE TITLE
Debug only works in fragment function

### ISSUE THREAD

**Issue by Adhil-Suresh** [arigo/ShaderDebugger#2]
Hi... Shader Debugger is only working in the fragment function, not in vertex function can you have a look. It becomes pink when we declare the uint root = DebugFragment(a.vertex); in the vertex function. Code given below
<img width="444" alt="ice_screenshot_20191009-095559" src="https://user-images.githubusercontent.com/43722374/66451643-065ac600-ea7b-11e9-870d-decdf7006537.png">

**Comment by arigo** [comment]
Done!  You need the new version and call ``uint root = DebugVertexO4(a.vertex);`` instead.  Thanks for your interest :-)
