### ISSUE TITLE
Not Working On Unity 2019

### ISSUE THREAD

**Issue by Adhil-Suresh** [arigo/ShaderDebugger#3]
The shader debugger is Working on unity 2018 but not on 2019 can you have a look. I am using
2019.2.9f1

**Comment by arigo** [comment]
It works for me.  I just tested it with Unity 2019.1.14f1 and 2019.2.11f1.  I guess something is different in your project.  I guess some setting somewhere is causing a bad interaction.  The next step would be if you could extract a smaller project from your project where the problem still occurs?  I would suggest: start with a copy of your project; remove *all* the assets apart from the shader that cannot be tested; add ShaderDebugger again; make a scene with a cube and give it a material with your shader.  If the problem still occurs, then send me the project and I'll see what is wrong in ShaderDebugger.

**Comment by Adhil-Suresh** [comment]
I just download the project and then a created an empty project in unity and added shaderdebugger folder to my project.Here it is Can you have Look Please
https://drive.google.com/open?id=11DXf7tBZlttnA819xQj-mQ5itIwR3bII
![Screenshot (1)](https://user-images.githubusercontent.com/43722374/68377070-c36e3a00-016f-11ea-9245-b66b55500397.png)

**Comment by arigo** [comment]
Apparently, if you install the package "2D Tilemap Editor" (from Window -> Package Manager), then it works again.  Now investigating WHY.

**Comment by arigo** [comment]
Fixed in c7e31f5.  Thanks!  I don't understand exactly why, but there are now two very similar SceneView events, one of which is deprecated; the difference is not documented; and the old one appears not to be called if you don't install "2D Tilemap Editor"...  but at least using the new one on Unity 2019 seems to always work.

**Comment by Adhil-Suresh** [comment]
Cool Thank You very much Working Fine
